name: Build dagger workflow
# Expects a PAT named 'GH_PAT' in Actions secrets

on: [push]

jobs:
  checkout-build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: maert/dagger-github-action@v1.3
        with:
          repo-token: ${{ secrets.GH_PAT }}
      
      - name: Init dagger
        run: |
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger project init
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger project update
          
      - name: Dagger do hello
        run: |
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger do hello
        
