name: Build dagger workflow
# Expects a PAT named 'GH_PAT' in Actions secrets

on: [push]

jobs:
  checkout-build-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: maert/dagger-github-action@v1.3
        with:
          dagger-repo: maert/dagger # my fork, dagger/dagger is default
          dagger-git-ref: 0d9365e18164cebc7ab7e692c1aeddc3502a32b7 # main is default
          repo-token: ${{ secrets.GH_PAT }} # optional, if needed
      
      - name: init dagger
        run: |
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger project init
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger project update
          
      - name: dagger do hello
        run: |
          ${{ github.workspace }}/src/dagger/cmd/dagger/dagger do hello
        
